### PR TITLE
[M1_TR-29] Create Template Components

### PR DESCRIPTION
**Pull request by arden-dave-sun**
### Related Issue
- Backlog Link: https://framgiaph.backlog.com/view/M1_TR-29

### Context
- Setup components for template layout for all pages, adding Navbar and Header

### Commands
- run the following commands
```
cd web
yarn dev
```
- go to `http://localhost:3000/`

### Test Executed
- [ ] Unit Test
- [ ] Functional Test

### Screenshot
image

https://github.com/framgia/sph-sim-jms/assets/111718037/abe31d16-1080-4227-bde9-b0327f287d9e

### Nature of task
- [ ] New Implementation
- [ ] Bug
- [ ] Refactoring

### Risks
- [ ] Affecting other functions

### CODE REVIEW

**Review by NiloJr-sun — DISMISSED** [review]

**Review by jeremiahC — APPROVED** [review]

**Review by jeremiahC — APPROVED** [review]
LGTM

**Review by jeremiahC — DISMISSED** [review]
LGTM

**Comment by jasonchuasun** [comment]
Replace the custom dropdown icon with MaterialUIs built-in icon_button.
Add spacing (8px) between the profile and dropdown_icon_button. See Figma design.
replace dropdown icon with mui_icon_button
spacing between profile and dropdown

Replace the edit icon with MaterialUIs built-in icon_button. Should be clickable. See Figma design.
replace edit icon with mui_icon_button

Menu button should be centered when collapsed. See Figma design.
centered menu icon

**Review by jasonchuasun — APPROVED** [review]
Approved.

**Pull request merged**
